
package mainpackage;
import java.text.*;
import java.awt.Toolkit;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.*;
import java.text.SimpleDateFormat;
import java.lang.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author rohith pavan
 */
public class Admin extends javax.swing.JFrame {
     Connection c;
 Statement stmt;
 ResultSet rs,com;
  String specialised="",user_id="",password1="",password2="",password3;
  String id;
  String name2="";
    boolean check1(String a)
    {
        int size=a.length();
        if(size>=8&&size<=30)
            return true;
           return false;
    }
    boolean check2(String a)
    {
        char arr[]=a.toCharArray();
        int size=a.length();
        for(int i=0;i<size;i++)
            if(arr[i]>='a'&&arr[i]<='z')
                return true;
        return false;
    }
    boolean check3(String a)
    {
          char arr[]=a.toCharArray();
        int size=a.length();
        for(int i=0;i<size;i++)
            if(arr[i]>='A'&&arr[i]<='Z')
                return true;
        return false;
    }
    boolean check4(String a)
    {
          char arr[]=a.toCharArray();
        int size=a.length();
        for(int i=0;i<size;i++)
            if(arr[i]=='!'||arr[i]=='@'||arr[i]=='#'||arr[i]=='$'||arr[i]=='&'||arr[i]=='*')
                return true;
        return false;
    }
    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
         setIconImage();
         try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        c=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital?autoReconnect=true&useSSL=false","root","1234");
        stmt=c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
    ResultSet.CONCUR_READ_ONLY);
        }
        catch(Exception e)
        {
          System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel23 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPanel7 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        jCheckBox6 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1520, 813));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1520, 813));
        setSize(new java.awt.Dimension(1520, 813));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("       ADD");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 120, 150, 50);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("   HOME");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 10, 110, 60);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("   DELETE");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 220, 150, 50);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("<html>COMPLAINT BOX</html>");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 330, 150, 60);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("   LOGOUT");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 610, 150, 50);

        jLabel30.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("<html>DOCTOR INFO</html>");
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel30MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel30MouseExited(evt);
            }
        });
        jPanel1.add(jLabel30);
        jLabel30.setBounds(10, 460, 150, 50);
        jPanel1.add(jDateChooser2);
        jDateChooser2.setBounds(530, 100, 130, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 170, 810);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Arial", 3, 150)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("<html>WELCOME</html><html>  ADMIN</html>");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(100, 20, 810, 390);

        jLabel8.setFont(new java.awt.Font("Arial", 3, 150)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("ADMIN");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(720, 280, 550, 250);

        jTabbedPane1.addTab("tab2", jPanel5);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Arial", 3, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("                   STAFF REGISTRATION PAGE");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(3, 5, 1300, 70);

        jPanel4.add(jPanel2);
        jPanel2.setBounds(0, 10, 1350, 90);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jTextField1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel3.add(jTextField1);
        jTextField1.setBounds(150, 20, 360, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("NAME:");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 20, 70, 30);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("AGE   :");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(20, 70, 60, 30);

        jTextField2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        jPanel3.add(jTextField2);
        jTextField2.setBounds(150, 70, 40, 30);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("GENDER :");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(20, 120, 90, 40);

        jRadioButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton1.setText("female");
        buttonGroup1.add(jRadioButton1);
        jPanel3.add(jRadioButton1);
        jRadioButton1.setBounds(150, 130, 100, 21);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton2.setText("male");
        jPanel3.add(jRadioButton2);
        jRadioButton2.setBounds(150, 150, 90, 21);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("<html>FATHER NAME :</html>");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(20, 250, 120, 50);
        jPanel3.add(jTextField3);
        jTextField3.setBounds(150, 260, 360, 30);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("<html>MOTHER NAME:<html/>");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(20, 320, 110, 50);
        jPanel3.add(jTextField4);
        jTextField4.setBounds(150, 340, 360, 30);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel16.setVisible(false);
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("<html>SPECIALISED IN:</html>");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(10, 500, 120, 60);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-NONE-", "CARDIOLOGIST", "DENTIST", "ENT SPECIALIST", "PSYCHIOTRISTS", "ORTHOPAEDIC SURGEON" }));
        jComboBox1.setVisible(false);
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(150, 510, 180, 30);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("ADDRESS:");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(20, 560, 120, 50);

        jTextArea1.setColumns(5);
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setLineWrap(true);
        jTextArea1.setToolTipText("");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(140, 570, 260, 100);

        jLabel22.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("SALARY:");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(20, 390, 110, 30);

        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });
        jPanel3.add(jTextField6);
        jTextField6.setBounds(150, 390, 70, 30);

        jDateChooser1.setDateFormatString("dd-MM-yyyy");
        jPanel3.add(jDateChooser1);
        jDateChooser1.setBounds(150, 182, 160, 30);

        jLabel23.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("<html>DATE OF BIRTH:</html>");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(20, 180, 110, 40);

        jLabel44.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("FIELD:");
        jPanel3.add(jLabel44);
        jLabel44.setBounds(20, 460, 80, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-none-", "Doctor", "staff_reciopnist", "staff_medicine", "staff_finance" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox3);
        jComboBox3.setBounds(150, 452, 170, 30);

        jPanel4.add(jPanel3);
        jPanel3.setBounds(50, 110, 520, 690);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(null);

        jTextField5.setText("Enter user id");
        jTextField5.setForeground(new java.awt.Color(102, 102, 102));
        jTextField5.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField5CaretUpdate(evt);
            }
        });
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });
        jPanel6.add(jTextField5);
        jTextField5.setBounds(50, 90, 280, 40);

        jPasswordField1.setText("Enter password");
        jPasswordField1.setEchoChar((char)0);
        jPasswordField1.setForeground(new java.awt.Color(102, 102, 102));
        jPasswordField1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jPasswordField1CaretUpdate(evt);
            }
        });
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        jPanel6.add(jPasswordField1);
        jPasswordField1.setBounds(50, 190, 280, 40);

        jPasswordField2.setText("Re_type password");
        jPasswordField2.setEchoChar((char)0);
        jPasswordField2.setForeground(new java.awt.Color(102, 102, 102));
        jPasswordField2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jPasswordField2CaretUpdate(evt);
            }
        });
        jPasswordField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField2FocusLost(evt);
            }
        });
        jPasswordField2.setEnabled(false);
        jPanel6.add(jPasswordField2);
        jPasswordField2.setBounds(50, 250, 280, 40);

        jPanel7.setVisible(false);
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(null);

        jCheckBox1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(204, 0, 0));
        jCheckBox1.setText("<html>the password length must between 8-30 characters</html>");
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseExited(evt);
            }
        });
        jPanel7.add(jCheckBox1);
        jCheckBox1.setBounds(10, 30, 360, 30);

        jCheckBox2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(204, 0, 0));
        jCheckBox2.setText("MUST CONTAIL ATLEAST 1 SMALL LETTER");
        jCheckBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCheckBox2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCheckBox2MouseExited(evt);
            }
        });
        jPanel7.add(jCheckBox2);
        jCheckBox2.setBounds(10, 70, 340, 21);

        jCheckBox3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(204, 0, 0));
        jCheckBox3.setText("MUST CONTAIN ATLEAST 1 CAPITAL");
        jCheckBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCheckBox3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCheckBox3MouseExited(evt);
            }
        });
        jPanel7.add(jCheckBox3);
        jCheckBox3.setBounds(10, 100, 320, 21);

        jCheckBox4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(204, 0, 0));
        jCheckBox4.setText("<html>SHOULD CONTAIN ATLEAST 1 SPECIAL CHARACTER I.E !,@,#,$,&,*.</html>");
        jCheckBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCheckBox4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCheckBox4MouseExited(evt);
            }
        });
        jPanel7.add(jCheckBox4);
        jCheckBox4.setBounds(10, 130, 360, 30);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 0, 0));
        jLabel19.setText("NOTE:");
        jPanel7.add(jLabel19);
        jLabel19.setBounds(10, 10, 60, 20);

        jPanel6.add(jPanel7);
        jPanel7.setBounds(350, 150, 380, 170);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 0, 0));
        jLabel20.setVisible(false);
        jLabel20.setText("USER ID ALREADY EXIST");
        jPanel6.add(jLabel20);
        jLabel20.setBounds(50, 140, 280, 30);

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 0, 0));
        jLabel21.setText("PASSWORD SHOULD SAME AS ABOVE");
        jLabel21.setVisible(false);
        jPanel6.add(jLabel21);
        jLabel21.setBounds(50, 300, 280, 30);

        jCheckBox5.setText("Show Password");
        jCheckBox5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox5StateChanged(evt);
            }
        });
        jPanel6.add(jCheckBox5);
        jCheckBox5.setBounds(50, 330, 170, 30);

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Arial", 3, 48)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CREATE");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel6.add(jButton1);
        jButton1.setBounds(60, 380, 230, 60);

        jPanel4.add(jPanel6);
        jPanel6.setBounds(580, 110, 750, 480);

        jTabbedPane1.addTab("tab1", jPanel4);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(null);

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(null);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("USER ID");
        jLabel26.setToolTipText("");
        jPanel8.add(jLabel26);
        jLabel26.setBounds(20, 130, 90, 40);

        jTextField8.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField8CaretUpdate(evt);
            }
        });
        jPanel8.add(jTextField8);
        jTextField8.setBounds(140, 130, 380, 40);

        jLabel28.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("<html>ADMIN PASSWORD:</html>");
        jPanel8.add(jLabel28);
        jLabel28.setBounds(10, 240, 120, 60);

        jPasswordField3.setEchoChar('\u26AB');
        jPanel8.add(jPasswordField3);
        jPasswordField3.setBounds(140, 250, 310, 40);

        jCheckBox6.setText("Show Password");
        jCheckBox6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox6StateChanged(evt);
            }
        });
        jPanel8.add(jCheckBox6);
        jCheckBox6.setBounds(140, 310, 160, 20);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Arial", 3, 48)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("REMOVE");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel8.add(jButton2);
        jButton2.setBounds(140, 370, 260, 60);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("In Valid id.!!!");
        jPanel8.add(jLabel12);
        jLabel12.setBounds(140, 180, 100, 20);

        jPanel9.add(jPanel8);
        jPanel8.setBounds(330, 180, 660, 570);

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));
        jPanel12.setLayout(null);

        jLabel25.setFont(new java.awt.Font("Arial", 3, 80)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 0, 0));
        jLabel25.setText("         STAFF REMOVAL PAGE");
        jPanel12.add(jLabel25);
        jLabel25.setBounds(3, 10, 1340, 80);

        jPanel9.add(jPanel12);
        jPanel12.setBounds(0, 0, 1340, 90);

        jTabbedPane1.addTab("tab3", jPanel9);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(null);

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));
        jPanel13.setLayout(null);

        jLabel29.setFont(new java.awt.Font("Arial", 3, 80)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 0, 0));
        jLabel29.setText("              COMPLAINT  BOX");
        jPanel13.add(jLabel29);
        jLabel29.setBounds(3, 6, 1330, 80);

        jPanel11.add(jPanel13);
        jPanel13.setBounds(0, 0, 1340, 90);

        jTextArea2.setLineWrap(true);
        jTextArea2.setColumns(20);
        jTextArea2.setEditable(false);
        jTextArea2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane4.setViewportView(jTextArea2);

        jPanel11.add(jScrollPane4);
        jScrollPane4.setBounds(30, 110, 860, 570);

        jButton3.setBackground(new java.awt.Color(0, 0, 204));
        jButton3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("<-PREV");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton3);
        jButton3.setBounds(600, 700, 120, 40);

        jButton4.setBackground(new java.awt.Color(0, 0, 204));
        jButton4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("NEXT->");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel11.add(jButton4);
        jButton4.setBounds(740, 700, 120, 40);

        jButton5.setBackground(new java.awt.Color(0, 204, 51));
        jButton5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("REMOVE");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel11.add(jButton5);
        jButton5.setBounds(30, 700, 140, 40);

        jTabbedPane1.addTab("tab5", jPanel11);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(null);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-none-" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel14.add(jComboBox2);
        jComboBox2.setBounds(70, 110, 170, 30);

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Select Doctor:");
        jPanel14.add(jLabel31);
        jLabel31.setBounds(70, 70, 170, 30);

        jPanel19.setLayout(null);

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Doctor id:");
        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel19.add(jLabel32);
        jLabel32.setBounds(30, 30, 150, 40);

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("<html>No_of_years worked:</html>");
        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel19.add(jLabel33);
        jLabel33.setBounds(30, 330, 240, 60);

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("<html>No of patients treated:</html>");
        jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel19.add(jLabel34);
        jLabel34.setBounds(30, 110, 240, 60);

        jLabel35.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel19.add(jLabel35);
        jLabel35.setBounds(330, 30, 210, 40);

        jLabel36.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel19.add(jLabel36);
        jLabel36.setBounds(330, 110, 110, 40);

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("No of operations:");
        jLabel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel19.add(jLabel37);
        jLabel37.setBounds(30, 190, 240, 40);

        jLabel38.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel19.add(jLabel38);
        jLabel38.setBounds(330, 190, 110, 40);

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Salary:");
        jLabel39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel19.add(jLabel39);
        jLabel39.setBounds(30, 270, 90, 40);

        jLabel40.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel19.add(jLabel40);
        jLabel40.setBounds(330, 270, 120, 40);

        jLabel41.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel19.add(jLabel41);
        jLabel41.setBounds(330, 430, 240, 40);

        jLabel42.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel19.add(jLabel42);
        jLabel42.setBounds(330, 340, 110, 40);

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setText("Specialization:");
        jLabel43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel19.add(jLabel43);
        jLabel43.setBounds(30, 430, 190, 40);

        jPanel14.add(jPanel19);
        jPanel19.setBounds(330, 160, 630, 510);

        jTabbedPane1.addTab("tab6", jPanel14);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(170, -40, 1340, 850);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);    
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(2);
         jTextField8.setText("");
         jPasswordField3.setText("");
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
         try {
             // TODO add your handling code here:
             jTabbedPane1.setSelectedIndex(3);
             stmt.executeUpdate("create table if not exists complaint(user_id varchar(30),com varchar(3000))");
             com=stmt.executeQuery("select * from complaint");
             if(com.next())
              jTextArea2.setText(com.getString(1)+"\n\n\n"+com.getString(2));
         } catch (Exception ex) {
             Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        
         dispose();
         new Loginpage().setVisible(true);
         try{
        
         }
         catch(Exception e)
         {
             System.out.println(e);
         }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTextField5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusGained
        // TODO add your handling code here:
           if(jTextField5.getText().equals("Enter user id")==true)
        {    
        jTextField5.setText("");
        jTextField5.setForeground(new java.awt.Color(0,0,0));
        }
    }//GEN-LAST:event_jTextField5FocusGained

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
        // TODO add your handling code here:
          if(jTextField5.getText().equals("")==true)
        {
        jTextField5.setText("Enter user id");
        jTextField5.setForeground(new java.awt.Color(102, 102, 102));
        }
    }//GEN-LAST:event_jTextField5FocusLost

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        // TODO add your handling code here:
         
         if(new String(jPasswordField1.getPassword()).equals("Enter password")==true&&jCheckBox5.isSelected()==false)
         {
         jPasswordField1.setText("");
         jPasswordField1.setEchoChar('\u26AB');
         jPasswordField1.setForeground(new java.awt.Color(0,0,0));
         }
          if(new String(jPasswordField1.getPassword()).equals("Enter password")==true&&jCheckBox5.isSelected()==true)
         {
         jPasswordField1.setText("");
         jPasswordField1.setEchoChar((char)0);
         jPasswordField1.setForeground(new java.awt.Color(0,0,0));
         }
          jPanel7.setVisible(true);
        
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
        // TODO add your handling code here:
         jPanel7.setVisible(false);
        if(new String(jPasswordField1.getPassword()).equals("")==true)
        {
            jPasswordField1.setText("Enter password");
            jPasswordField1.setEchoChar((char)0);
            jPasswordField1.setForeground(new java.awt.Color(102, 102, 102));
        }
        
    }//GEN-LAST:event_jPasswordField1FocusLost

    private void jPasswordField1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jPasswordField1CaretUpdate
        // TODO add your handling code here:

        boolean length,small,large,special;
         length=check1(new String(jPasswordField1.getPassword()));
         small=check2(new String(jPasswordField1.getPassword()));
         large=check3(new String(jPasswordField1.getPassword()));
         special=check4(new String(jPasswordField1.getPassword()));
         jCheckBox1.setSelected(length);
         jCheckBox2.setSelected(small);
         jCheckBox3.setSelected(large);
         jCheckBox4.setSelected(special);
         if(jCheckBox1.isSelected())
              jCheckBox1.setForeground(new java.awt.Color(0, 204, 0));
         else
          jCheckBox1.setForeground(new java.awt.Color(204,0, 0)); 
          if(jCheckBox2.isSelected())
              jCheckBox2.setForeground(new java.awt.Color(0, 204, 0));
          else
             jCheckBox2.setForeground(new java.awt.Color(204,0, 0));
           if(jCheckBox3.isSelected())
              jCheckBox3.setForeground(new java.awt.Color(0, 204, 0));
           else
             jCheckBox3.setForeground(new java.awt.Color(204,0, 0));
            if(jCheckBox4.isSelected())
              jCheckBox4.setForeground(new java.awt.Color(0, 204, 0));
            else 
             jCheckBox4.setForeground(new java.awt.Color(204,0, 0));  
            if(jCheckBox1.isSelected()&&jCheckBox2.isSelected()&&jCheckBox4.isSelected()&&jCheckBox3.isSelected())
                jPasswordField2.setEnabled(true);
            else
            {
                jPasswordField2.setText("Re_type password");
                  jPasswordField2.setEnabled(false);
                  jPasswordField2.setEchoChar((char)0);
            }
    }//GEN-LAST:event_jPasswordField1CaretUpdate

    private void jPasswordField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2FocusGained
        // TODO add your handling code here:
          if(new String(jPasswordField2.getPassword()).equals("Re_type password")==true&&jCheckBox5.isSelected()==false)
        {
         jPasswordField2.setText("");
         jPasswordField2.setEchoChar('\u26AB');
         jPasswordField2.setForeground(new java.awt.Color(0,0,0));
        }
         if(new String(jPasswordField2.getPassword()).equals("Re_type password")==true&&jCheckBox5.isSelected()==true)
        {
         jPasswordField2.setText("");
         jPasswordField2.setEchoChar((char)0);
         jPasswordField2.setForeground(new java.awt.Color(0,0,0));
        }
            password1=new String(jPasswordField1.getPassword());
    }//GEN-LAST:event_jPasswordField2FocusGained

    private void jPasswordField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2FocusLost
        // TODO add your handling code here:
        if(new String(jPasswordField2.getPassword()).equals("")==true)
        {
           jPasswordField2.setText("Re_type password");
        jPasswordField2.setEchoChar((char)0);
        jPasswordField2.setForeground(new java.awt.Color(102, 102, 102));
        }
    }//GEN-LAST:event_jPasswordField2FocusLost

    private void jCheckBox5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox5StateChanged
        // TODO add your handling code here:
        if(jCheckBox5.isSelected()==true)
        {
            jPasswordField1.setEchoChar((char)0);
            jPasswordField2.setEchoChar((char)0);
        }
        if(jCheckBox5.isSelected()==false&&(new String(jPasswordField1.getPassword()).equals("Enter password"))==false)
        {
            jPasswordField1.setEchoChar('\u26AB');
          
        }
        if(jCheckBox5.isSelected()==false&&(new String(jPasswordField2.getPassword()).equals("Re_type password"))==false)
             jPasswordField2.setEchoChar('\u26AB');
    }//GEN-LAST:event_jCheckBox5StateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String name="",gender="",f_name="",m_name="",field="",address="";
        String dob="",doj="";
        int salary=0,age=0;
        name=jTextField1.getText();
        if(jTextField2.getText().equals("")==false)
        age=Integer.parseInt(jTextField2.getText());
        if(jRadioButton1.isSelected()==true)
           gender="female";
       if(jRadioButton2.isSelected()==true)
            gender="male";
       if(jDateChooser1.getDate()!=null)
        dob=new SimpleDateFormat("yyyy-MM-dd").format(jDateChooser1.getDate());
        f_name=jTextField3.getText();
        m_name=jTextField4.getText();
         if(jTextField6.getText().equals("")==false)
       salary=Integer.parseInt(jTextField6.getText());
        field=String.valueOf(jComboBox3.getSelectedItem());
        address=jTextArea1.getText();
        java.util.Date date1=new java.util.Date();
        doj=new SimpleDateFormat("yyyy-MM-dd").format(date1);
        password1=new String(jPasswordField1.getPassword());
        password2=new String(jPasswordField2.getPassword());
        if(jComboBox1.isVisible())
        specialised=String.valueOf(jComboBox1.getSelectedItem());
        if(name.equals("")==false&&jTextField2.getText().equals("")==false&&gender.equals("")==false&&jDateChooser1.getDate()!=null&&f_name.equals("")==false&&m_name.equals("")==false&&jTextField6.getText().equals("")==false&&field.equalsIgnoreCase("-none-")!=true&&address.equals("")==false&&password1.equals("Enter password")==false&&password2.equals("Re_type password")==false&&password1.equals(password2)==true&&user_id.equals("Enter user id")==false&&jLabel20.isVisible()==false&&jLabel21.isVisible()==false&&((field.equalsIgnoreCase("doctor")==true&&specialised.equalsIgnoreCase("-none-")==false)||field.equalsIgnoreCase("doctor")==false))
        {
            try{
                stmt.executeUpdate("insert into info values('"+user_id+"','"+name+"','"+age+"','"+gender+"','"+dob+"','"+f_name+"','"+m_name+"','"+salary+"','"+field+"','"+specialised+"','"+address+"','"+doj+"')");
                stmt.executeUpdate("insert into user values('"+user_id+"','"+password1+"','"+field+"')");
                 if(field.equalsIgnoreCase("doctor")==true) 
                 {
                    
                     stmt.executeUpdate("create table if not exists patient (Patient_name varchar(30),patient_id varchar(20) primary key,age int,gender varchar(10),problem varchar(500),description varchar(500),date date,number varchar(10),patient_regard varchar(20),time Time,doctor_id varchar(30));");         
                 }
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
               JOptionPane.showMessageDialog(jPanel4,"Successfully register");  
               jTextField1.setText("");
               jTextField2.setText("");
               if(jRadioButton1.isSelected())
               jRadioButton1.setSelected(false);
               if(jRadioButton2.isSelected())
               jRadioButton2.setSelected(false);
               jTextField3.setText("");
               jTextField4.setText("");
               jTextField6.setText("");
               jComboBox3.setSelectedIndex(0);
               jComboBox1.setVisible(false);
               jTextArea1.setText("");
               jTextField5.setText("Enter user id");
               jPasswordField1.setText("Enter password");
               jPasswordField1.setEchoChar((char)0);
               jPasswordField2.setText("Re_type password");
               jPasswordField2.setEchoChar((char)0);
                jDateChooser1.setDate(null);
                if(jCheckBox5.isSelected())
                    jCheckBox5.setSelected(false);
                buttonGroup1.clearSelection();
                user_id="";
                specialised="";
                password1="";
                password2="";
                
        }
        else
        {
             JOptionPane.showMessageDialog(jPanel4,"fll all field correctly","Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jCheckBox6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox6StateChanged
        // TODO add your handling code here:
        if(jCheckBox6.isSelected()==true)
            jPasswordField3.setEchoChar((char)0);
        else
            jPasswordField3.setEchoChar('\u26AB');
    }//GEN-LAST:event_jCheckBox6StateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(4);
         jComboBox2.removeAllItems();
         jComboBox2.addItem("-none-");
  
         try{
         rs=stmt.executeQuery("Select * from info where field='Doctor'");
         while(rs.next())
         {
             jComboBox2.addItem(rs.getString("user_id")+" "+rs.getString("name"));
         }
         }
         catch(Exception e)
         {
             System.out.println(e);
         }
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        int val=0;
        String today=new SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date());
        if(jComboBox2.getSelectedItem()!=null)
        if(jComboBox2.getSelectedItem().toString().equalsIgnoreCase("-none-")==false)
        {
            String str[]=jComboBox2.getSelectedItem().toString().split(" ");
            jLabel35.setText(str[0]);
            try{
                rs=stmt.executeQuery("select count(*) from patient where doctor_id='"+str[0]+"' and date<'"+today+"'");
                if(rs.next())
                    jLabel36.setText(rs.getString(1));
                rs=stmt.executeQuery("select count(*) from patient where doctor_id='"+str[0]+"' and date<'"+today+"' and patient_regard='operation'");
                if(rs.next())
                    jLabel38.setText(rs.getString(1));
                rs=stmt.executeQuery("select * from info where user_id='"+str[0]+"'");
                if(rs.next())
                {
                    String join[]=rs.getString("date_of_join").split("-");
                    String today2[]=today.split("-");
                     val=Integer.parseInt(today2[0])-Integer.parseInt(join[0]);
                }
                if(val<=0)
                    jLabel42.setText("<1");
                else
                    jLabel42.setText(Integer.toString(val));
                rs=stmt.executeQuery("select * from info where user_id='"+str[0]+"'");
                if(rs.next())
                {
                    jLabel40.setText(rs.getString("salary"));
                    jLabel41.setText(rs.getString("specialised"));
                }
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
            
        }
        else
        {
             jLabel35.setText("");
              jLabel36.setText("");
               jLabel38.setText("");
                jLabel40.setText("");
                 jLabel41.setText("");
                  jLabel42.setText("");
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jCheckBox1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseEntered
        // TODO add your handling code here:
        jCheckBox1.setEnabled(false);
    }//GEN-LAST:event_jCheckBox1MouseEntered

    private void jCheckBox1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseExited
        // TODO add your handling code here:
         jCheckBox1.setEnabled(true);
    }//GEN-LAST:event_jCheckBox1MouseExited

    private void jCheckBox2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox2MouseEntered
        // TODO add your handling code here:
         jCheckBox2.setEnabled(false);
    }//GEN-LAST:event_jCheckBox2MouseEntered

    private void jCheckBox2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox2MouseExited
        // TODO add your handling code here:
         jCheckBox2.setEnabled(true);
    }//GEN-LAST:event_jCheckBox2MouseExited

    private void jCheckBox3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox3MouseExited
        // TODO add your handling code here:
         jCheckBox3.setEnabled(true);
    }//GEN-LAST:event_jCheckBox3MouseExited

    private void jCheckBox3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox3MouseEntered
        // TODO add your handling code here:
         jCheckBox3.setEnabled(false);
    }//GEN-LAST:event_jCheckBox3MouseEntered

    private void jCheckBox4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox4MouseEntered
        // TODO add your handling code here:
         jCheckBox4.setEnabled(false);
    }//GEN-LAST:event_jCheckBox4MouseEntered

    private void jCheckBox4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox4MouseExited
        // TODO add your handling code here:
         jCheckBox4.setEnabled(true);
    }//GEN-LAST:event_jCheckBox4MouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
         jLabel2.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
          jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
         jLabel1.setForeground(new java.awt.Color(0, 0, 0));
          
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        
          jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
         jLabel3.setForeground(new java.awt.Color(0, 0, 0));
         
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
         
          jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
         jLabel5.setForeground(new java.awt.Color(0, 0, 0));
          
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        // TODO add your handling code here:
        
          jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel30MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseEntered
        // TODO add your handling code here:
         jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        
    }//GEN-LAST:event_jLabel30MouseEntered

    private void jLabel30MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseExited
        // TODO add your handling code here:
          jLabel30.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel30MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
         jLabel6.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
          jLabel6.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel6MouseExited

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
          String field;
        field=String.valueOf(jComboBox3.getSelectedItem());
        if(field.equalsIgnoreCase("doctor")==true)
        {
            jLabel16.setVisible(true);
            jComboBox1.setVisible(true);
            
        }
        else
        {
             jLabel16.setVisible(false);
            jComboBox1.setVisible(false);
            specialised="";
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
         if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')||(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE)) 
               jTextField2.setEditable(true);
         else
               jTextField2.setEditable(false);
        
        
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
        // TODO add your handling code here:
            if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')||(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE)) 
               jTextField6.setEditable(true);
         else
               jTextField6.setEditable(false);
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        // TODO add your handling code here:
         int age=Integer.parseInt(jTextField2.getText());
          if(age<23||age>70)
        {
            jTextField2.setText("");
             JOptionPane.showMessageDialog(jPanel4,"inValid age","Alert",JOptionPane.WARNING_MESSAGE);
             
        }
    }//GEN-LAST:event_jTextField2FocusLost

    private void jPasswordField2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jPasswordField2CaretUpdate
        // TODO add your handling code here:
       password2=new String(jPasswordField2.getPassword());
       if(password1!=null&&password2!=null)
       {
       if(password1.equals(password2)==true)
           jLabel21.setVisible(false);
       if(jPasswordField2.isEnabled()==true&&password1.equals(password2)==false)
           jLabel21.setVisible(true);
       }
    }//GEN-LAST:event_jPasswordField2CaretUpdate

    private void jTextField5CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField5CaretUpdate
        // TODO add your handling code here:
        
        user_id=jTextField5.getText();
        try{
        rs=stmt.executeQuery("select count(user_id) from user where user_id='"+user_id+"'");
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        int count=1;
        try{
        while(rs.next())
            count=Integer.parseInt(rs.getString(1));
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        if(count!=0)
            jLabel20.setVisible(true);
        else
            jLabel20.setVisible(false);
    }//GEN-LAST:event_jTextField5CaretUpdate

    private void jTextField8CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField8CaretUpdate
        // TODO add your handling code here:
        
        id=jTextField8.getText();
        try{
        rs=stmt.executeQuery("select * from info where user_id='"+id+"'");
        if(rs.next())
        {
         name2=rs.getString(2);   
        }
        else
            name2="";
        }
        catch(Exception e)
        {
            System.out.print(e);
        }
        if(name2.equals("")==true)
            jLabel12.setVisible(true);
        else
            jLabel12.setVisible(false);
        
    }//GEN-LAST:event_jTextField8CaretUpdate

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        StringBuffer sb=new StringBuffer();
        String del="";
        int val1=0,val2=0,val3=0;
          try{
        rs=stmt.executeQuery("select * from user where lower(field)='admin'");
        while(rs.next())
        {
         password3=rs.getString(2);   
        }
        }
        catch(Exception e)
        {
            System.out.print(e);
        }
        String password4=new String(jPasswordField3.getPassword());
        if(password3.equals(password4)==true)
        {
            try{
                rs=stmt.executeQuery("select * from info where user_id='"+id+"'");
                if(rs.next())
                   del= rs.getString("field");
           val1= stmt.executeUpdate("delete from user where user_id='"+id+"'");
            val2=stmt.executeUpdate("delete from info where user_id='"+id+"'");
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
            if(val1!=0&&val2!=0&&val3==0)
                JOptionPane.showMessageDialog(jPanel9,"Successfully removed");
            else
                JOptionPane.showMessageDialog(jPanel9,"Something failed","Alert",JOptionPane.WARNING_MESSAGE);
        
         jTextField8.setText("");
         jPasswordField3.setText("");
         name2="";
         password3="";
         if(jCheckBox6.isSelected()==true)
             jCheckBox6.setSelected(false);
        }
        else
        {
             JOptionPane.showMessageDialog(jPanel9,"inValid password","Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        try{
            if(com.previous())
                jTextArea2.setText(com.getString(1)+"\n\n\n"+com.getString(2));
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        try{
            if(com.next())
                jTextArea2.setText(com.getString(1)+"\n\n\n"+com.getString(2));
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        String user_id,prob;
        try{
            StringTokenizer str=new StringTokenizer(jTextArea2.getText(),"\n\n\n");
                user_id=str.nextToken();
                prob=str.nextToken();
               stmt.executeUpdate("delete from complaint where user_id='"+user_id+"' and com='"+prob+"'");
               JOptionPane.showMessageDialog(this,"Successfully Removed");
               com=stmt.executeQuery("select * from complaint");
               if(com.next())
               {
                    jTextArea2.setText(com.getString(1)+"\n\n\n"+com.getString(2));
               }
              else if(com.previous())
               {
                    jTextArea2.setText(com.getString(1)+"\n\n\n"+com.getString(2));
               }
               else
              {
                  jTextArea2.setText("");
              }
   
           
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }
    private void setIconImage() {
            setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
