/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainpackage;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rohith pavan
 */
public class staff_medicine extends javax.swing.JFrame {

    /**
     * Creates new form staff_medicine
     */
      Connection c;
 Statement stmt;
 ResultSet rs,check;
   DefaultListModel model1=new DefaultListModel();
   DefaultListModel model2=new DefaultListModel();
   DefaultTableModel model3;
    public staff_medicine() {
        initComponents();
        setIconImage();
         try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        c=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital?autoReconnect=true&useSSL=false","root","1234");
        stmt=c.createStatement();
           stmt.executeUpdate("create table if not exists medicine_patient(med_qua varchar(120),total_price float,patient_id varchar(30),patient_name varchar(30),prescripted_by varchar(20),date date)");
           stmt.executeUpdate("create table if not exists medicine(name varchar(30),quantity int,no_of_tablets_per_batch int,price_of_each_batch float,expiry_date date)");
          rs=stmt.executeQuery("select * from info where field='Doctor'");
          jComboBox1.addItem("--none--");
           while(rs.next())
          jComboBox1.addItem(rs.getString(1)+"  "+rs.getString(2));
           jDateChooser2.setDate(new java.util.Date());
          model3=(DefaultTableModel)jTable1.getModel();
         
         }
        
        catch(Exception e)
        {
          System.out.println(e);
        }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel43 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jTextField8 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>(model1);
        jButton6 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel36 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 800));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1500, 800));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("    HOME");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 140, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MEDICINE GIVEN ");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(7, 150, 160, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("      SEARCH");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 250, 160, 40);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("     COMPLAINT");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 350, 170, 40);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("  MEDICINE LIST");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(7, 450, 160, 40);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("  LOGOUT");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 700, 160, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 170, 800);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1340, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 807, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab5", jPanel7);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jPanel2.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("NAME OF MEDICINE:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(130, 30, 250, 30);

        jTextField1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField1CaretUpdate(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(140, 70, 370, 40);

        jLabel8.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("PRICE:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(150, 120, 80, 30);
        jPanel2.add(jTextField2);
        jTextField2.setBounds(150, 150, 100, 30);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(0, 300, 670, 3);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("PATIENT ID:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(50, 330, 140, 40);

        jTextField3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField3CaretUpdate(evt);
            }
        });
        jPanel2.add(jTextField3);
        jTextField3.setBounds(50, 370, 180, 40);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("PATIENT NAME:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(50, 420, 186, 40);
        jPanel2.add(jTextField4);
        jTextField4.setBounds(50, 470, 300, 40);

        jButton3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("SAVE");
        jButton3.setBorder(null);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(530, 410, 90, 30);

        jButton4.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("CANCEL");
        jButton4.setToolTipText("");
        jPanel2.add(jButton4);
        jButton4.setBounds(530, 460, 100, 30);

        jLabel13.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("QUANTITY:");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(280, 120, 110, 30);

        jTextField7.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField7CaretUpdate(evt);
            }
        });
        jPanel2.add(jTextField7);
        jTextField7.setBounds(290, 150, 60, 30);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("PRESCRIPTED BY:");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(60, 530, 200, 40);

        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(50, 580, 210, 40);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("DATE:");
        jPanel2.add(jLabel28);
        jLabel28.setBounds(60, 640, 100, 40);
        jPanel2.add(jDateChooser2);
        jDateChooser2.setBounds(50, 680, 240, 40);

        jLabel43.setVisible(false);
        jLabel43.setForeground(new java.awt.Color(204, 0, 0));
        jLabel43.setText("medicine not found");
        jPanel2.add(jLabel43);
        jLabel43.setBounds(350, 40, 170, 20);

        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("* does not exist");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(240, 366, 150, 20);

        jPanel3.add(jPanel2);
        jPanel2.setBounds(370, 20, 730, 770);

        jTabbedPane1.addTab("tab2", jPanel3);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(null);

        jButton8.setText("Search");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jPanel8.add(jButton8);
        jButton8.setBounds(1060, 70, 75, 30);

        jTextField1.setForeground(new java.awt.Color(102,102,102));
        jTextField5.setText("Enter id");
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });
        jPanel8.add(jTextField5);
        jTextField5.setBounds(1060, 20, 160, 30);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name of patient", "Name of medicine", "Quantity", "Prescripted by", "Date", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setShowHorizontalLines(true);
        jTable1.setShowVerticalLines(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 970, 690);

        jPanel8.add(jPanel4);
        jPanel4.setBounds(50, 10, 990, 710);

        jTabbedPane1.addTab("tab5", jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(null);

        jTextArea3.setLineWrap(true);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        jPanel9.add(jScrollPane4);
        jScrollPane4.setBounds(20, 30, 530, 330);

        jButton5.setBackground(new java.awt.Color(0, 102, 0));
        jButton5.setFont(new java.awt.Font("Arial", 3, 28)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("COMPLAINT");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel9.add(jButton5);
        jButton5.setBounds(340, 370, 200, 60);

        jTabbedPane1.addTab("tab3", jPanel9);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jTextField1.setForeground(new java.awt.Color(102,102,102));
        jTextField8.setText("Enter name");
        jTextField8.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField8CaretUpdate(evt);
            }
        });
        jTextField8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField8FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField8FocusLost(evt);
            }
        });
        jPanel5.add(jTextField8);
        jTextField8.setBounds(1140, 20, 160, 30);

        jPanel6.setVisible(false);
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("QUANTITY:");
        jPanel6.add(jLabel20);
        jLabel20.setBounds(30, 10, 120, 40);

        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel21);
        jLabel21.setBounds(30, 60, 110, 30);

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("DATE:");
        jPanel6.add(jLabel34);
        jLabel34.setBounds(30, 110, 100, 30);

        jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel35);
        jLabel35.setBounds(30, 160, 130, 30);

        jLabel38.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("NO OF TABLETS FOR BATCH:");
        jPanel6.add(jLabel38);
        jLabel38.setBounds(30, 220, 280, 30);

        jLabel39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel39);
        jLabel39.setBounds(30, 270, 140, 40);

        jLabel40.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("PRICE OF EACH BATCH:");
        jPanel6.add(jLabel40);
        jLabel40.setBounds(30, 330, 270, 40);

        jLabel41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel41);
        jLabel41.setBounds(30, 370, 150, 40);

        jPanel5.add(jPanel6);
        jPanel6.setBounds(750, 20, 330, 460);

        jPanel10.setVisible(false);
        jPanel10.setLayout(null);

        jScrollPane3.setViewportView(jList4);

        jPanel10.add(jScrollPane3);
        jScrollPane3.setBounds(10, 20, 150, 250);

        jButton6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("DELETE");
        jButton6.setBorder(null);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jPanel10.add(jButton6);
        jButton6.setBounds(190, 220, 110, 40);

        jLabel23.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 0, 0));
        jLabel23.setText("<html>LIST OF MEDICINE EXPIRES WITHIN 5 DAYS</html>");
        jPanel10.add(jLabel23);
        jLabel23.setBounds(180, 20, 280, 100);

        jPanel5.add(jPanel10);
        jPanel10.setBounds(30, 20, 480, 290);

        jPanel11.setLayout(null);

        jLabel25.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("QUANTITY:");
        jPanel11.add(jLabel25);
        jLabel25.setBounds(40, 260, 120, 40);

        jLabel27.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("NAME");
        jPanel11.add(jLabel27);
        jLabel27.setBounds(30, 30, 130, 40);

        jButton7.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setText("ADD");
        jButton7.setBorder(null);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jPanel11.add(jButton7);
        jButton7.setBounds(290, 350, 140, 40);

        jLabel22.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("EXPIRY DATE:");
        jPanel11.add(jLabel22);
        jLabel22.setBounds(30, 310, 130, 30);

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel11.add(jTextField9);
        jTextField9.setBounds(290, 30, 370, 30);

        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField10KeyPressed(evt);
            }
        });
        jPanel11.add(jTextField10);
        jTextField10.setBounds(290, 90, 90, 30);
        jPanel11.add(jDateChooser1);
        jDateChooser1.setBounds(290, 300, 150, 30);

        jLabel36.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("NO OF TABLETS PER BATCH");
        jPanel11.add(jLabel36);
        jLabel36.setBounds(10, 200, 270, 30);

        jTextField11.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField11CaretUpdate(evt);
            }
        });
        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField11KeyPressed(evt);
            }
        });
        jPanel11.add(jTextField11);
        jTextField11.setBounds(290, 200, 90, 30);

        jLabel37.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("PRICE OF EACH BATCH:");
        jLabel37.setToolTipText("");
        jPanel11.add(jLabel37);
        jLabel37.setBounds(10, 90, 230, 30);
        jPanel11.add(jTextField12);
        jTextField12.setBounds(290, 260, 90, 30);

        jLabel42.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("NO OF BATCHES:");
        jPanel11.add(jLabel42);
        jLabel42.setBounds(20, 150, 230, 30);

        jTextField13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField13KeyPressed(evt);
            }
        });
        jPanel11.add(jTextField13);
        jTextField13.setBounds(290, 150, 90, 30);

        jPanel5.add(jPanel11);
        jPanel11.setBounds(10, 380, 680, 430);

        jLabel33.setFont(new java.awt.Font("Arial", 2, 48)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("ADD MEDICINES:");
        jPanel5.add(jLabel33);
        jLabel33.setBounds(40, 320, 540, 50);

        jTabbedPane1.addTab("tab4", jPanel5);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(170, -40, 1340, 840);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(1);
         try{
          
         }
         catch(Exception e)
         {
             System.out.println(e);
         }
         
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
      
         jTabbedPane1.setSelectedIndex(4);
           Calendar calendar = Calendar.getInstance();
    java.util.Date today = calendar.getTime();
    calendar.add(Calendar.DAY_OF_YEAR, 5);
    java.util.Date tomorrow = calendar.getTime();
    String str=new SimpleDateFormat("yyyy-MM-dd").format(tomorrow);
         try
         {
             rs=stmt.executeQuery("select * from medicine where expiry_date>='"+new SimpleDateFormat("yyyy-MM-dd").format(today)+"'&&expiry_date<='"+str+"'");
             while(rs.next())
             model1.addElement(rs.getString("name"));
             if(jList4.getModel().getSize()>0)
             {
                   jPanel10.setVisible(true);
             }
         }
         catch(Exception e)
         {
             System.out.println(e);
         }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        dispose();
        new Loginpage().setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
          jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jTextField8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField8FocusGained
        // TODO add your handling code here:
        if(jTextField8.getText().equals("Enter name")==true)
        {
            jTextField8.setText("");
            jTextField8.setForeground(new java.awt.Color(0,0,0));
        }
    }//GEN-LAST:event_jTextField8FocusGained

    private void jTextField8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField8FocusLost
        // TODO add your handling code here:
        if(jTextField8.getText().equals("")==true)
        {
            jTextField8.setText("Enter name");
            jTextField8.setForeground(new java.awt.Color(102,102,102));
        }
    }//GEN-LAST:event_jTextField8FocusLost

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
          jLabel1.setForeground(new java.awt.Color(0, 0, 0));
     
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
         jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
          jLabel2.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
         jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
          jLabel3.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
         jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
          jLabel4.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
         jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
          jLabel5.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        // TODO add your handling code here:
         jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
          jLabel6.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
         jLabel6.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel6MouseExited

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        try{
            if(jTextField9.getText().equals("")==false&&jTextField10.getText().equals("")==false&&jTextField11.getText().equals("")==false&&jTextField12.getText().equals("")==false&&jTextField13.getText().equals("")==false&&jDateChooser1.getDate()!=null)
            
            {
                check=stmt.executeQuery("select * from medicine where name='"+jTextField9.getText()+"'");
                        if(check.next())
                        {
                            stmt.executeUpdate("update medicine set quantity="+Integer.parseInt(jTextField12.getText())+",no_of_tablets_per_batch="+Integer.parseInt(jTextField11.getText())+",price_of_each_batch="+Float.parseFloat(jTextField10.getText())+",expiry_date='"+new SimpleDateFormat("yyyy-MM-dd").format(jDateChooser1.getDate())+"' where name='"+jTextField9.getText()+"'");
                            JOptionPane.showMessageDialog(this,"updated successfully");
                        }
                        else{
                        stmt.executeUpdate("insert into medicine values('"+jTextField9.getText()+"',"+Integer.parseInt(jTextField12.getText())+","+Integer.parseInt(jTextField11.getText())+","+Float.parseFloat(jTextField10.getText())+",'"+new SimpleDateFormat("yyyy-MM-dd").format(jDateChooser1.getDate())+"')");
            JOptionPane.showMessageDialog(this,"saved successfully");}
            jTextField9.setText("");
              jTextField10.setText("");
                jTextField11.setText("");
                  jTextField12.setText("");
                    jTextField13.setText("");
                    jDateChooser1.setDate(null);
                    }
            else
            {
                JOptionPane.showMessageDialog(this,"enter all fields","Warning",JOptionPane.WARNING_MESSAGE);
            }
                    }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton7MouseClicked

    private void jTextField11CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField11CaretUpdate
        // TODO add your handling code here:
        if(jTextField13.getText().equals("")==false)
        {
             if(jTextField11.getText().equals("")==false)
             {
                 jTextField12.setText(Integer.toString(Integer.parseInt(jTextField11.getText())*Integer.parseInt(jTextField13.getText())));
             }
             else
                 jTextField12.setText("");
        }
    }//GEN-LAST:event_jTextField11CaretUpdate

    private void jTextField10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyPressed
        // TODO add your handling code here:
         if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')||(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE)) 
               jTextField10.setEditable(true);
         else
               jTextField10.setEditable(false);
    }//GEN-LAST:event_jTextField10KeyPressed

    private void jTextField11KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyPressed
        // TODO add your handling code here:
         if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')||(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE)) 
               jTextField11.setEditable(true);
         else
               jTextField11.setEditable(false);
    }//GEN-LAST:event_jTextField11KeyPressed

    private void jTextField13KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField13KeyPressed
        // TODO add your handling code here:
         if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')||(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE)) 
               jTextField13.setEditable(true);
         else
               jTextField13.setEditable(false);
    }//GEN-LAST:event_jTextField13KeyPressed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        String str=jList4.getSelectedValue();
        try{
            stmt.executeUpdate("delete from medicine where name='"+str+"'");
            JOptionPane.showMessageDialog(this,"removed");
            model1.remove(jList4.getSelectedIndex());
            if(jList4.getModel().getSize()<=0)
                jPanel10.setVisible(false);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jTextField8CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField8CaretUpdate
        // TODO add your handling code here:
        try{
            rs=stmt.executeQuery("select count(name) from medicine where name='"+jTextField8.getText()+"'");
            if(rs.next())
            {
                if(Integer.parseInt(rs.getString(1))>0)
                { jPanel6.setVisible(true);
            
                    rs=stmt.executeQuery("select * from medicine where name='"+jTextField8.getText()+"'");
                   if(rs.next())
                   {
                    jLabel21.setText(rs.getString("quantity"));
                     jLabel35.setText(rs.getString("expiry_date"));
                      jLabel39.setText(rs.getString(3));
                      jLabel41.setText(rs.getString(4));
                   }        
                }
                else
                {
                    jPanel6.setVisible(false);
                     jLabel21.setText("");
                     jLabel35.setText("");
                      jLabel39.setText("");
                      jLabel41.setText("");
                }
                }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jTextField8CaretUpdate

    private void jTextField1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField1CaretUpdate
        // TODO add your handling code here:
         try{
            rs=stmt.executeQuery("select count(name) from medicine where name='"+jTextField1.getText()+"'");
            if(rs.next())
            {
                if(Integer.parseInt(rs.getString(1))>0)
                jLabel43.setVisible(false);
                else
                jLabel43.setVisible(true);
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jTextField1CaretUpdate

    private void jTextField7CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField7CaretUpdate
        // TODO add your handling code here:
        float a,b;
        if(jLabel43.isVisible()==true)
        {
            jTextField2.setText("");
        }
        else
        {
            try{
                rs=stmt.executeQuery("select * from medicine where name='"+jTextField1.getText()+"'");
                if(rs.next())
                {
                    a=Float.parseFloat(rs.getString(3));
                    b=Float.parseFloat(rs.getString(4));
                    if(jTextField7.getText().equals("")==false)
                    {
                        jTextField2.setText(Float.toString((b/a)*Float.parseFloat(jTextField7.getText())));
                    }
                    else
                        jTextField2.setText("");
                }
            }
            catch(Exception e)
            {
                System.out.print(e);
            }
        }
    }//GEN-LAST:event_jTextField7CaretUpdate

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        
        int i;
        if(jLabel43.isVisible()==false&&jTextField2.getText().equals("")==false&&jTextField7.getText().equals("")==false&&jDateChooser2.getDate()!=null&&jTextField3.getText().equals("")==false&&jTextField4.getText().equals("")==false&&jComboBox1.getSelectedIndex()>0&&jLabel9.isVisible()==false)
        {
            try{
               
                    check=stmt.executeQuery("select * from medicine where name='"+jTextField1.getText()+"'");
                    if(check.next())
                    if(Integer.parseInt(check.getString(2))-Integer.parseInt(jTextField7.getText())>=0)
                    {
                    stmt.executeUpdate("insert into medicine_patient values('"+jTextField1.getText()+" "+jTextField2.getText()+" "+jTextField7.getText()+"',"+Float.parseFloat(jTextField2.getText())+",'"+jTextField3.getText()+"','"+jTextField4.getText()+"','"+jComboBox1.getSelectedItem().toString()+"','"+new SimpleDateFormat("yyyy-MM-dd").format(jDateChooser2.getDate())+"')");
                    stmt.executeUpdate("update medicine set quantity=quantity-'"+Integer.parseInt(jTextField7.getText())+"' where name='"+jTextField1.getText()+"'");
                     JOptionPane.showMessageDialog(this,"Saved");
                     jTextField1.setText("");
                     jTextField2.setText("");
                jTextField7.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jComboBox1.setSelectedIndex(0);
                    }
                    else
                        JOptionPane.showMessageDialog(this,"Not Enough Quantity","Error",JOptionPane.WARNING_MESSAGE);
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
        }
        else
             JOptionPane.showMessageDialog(this,"fill all fields","alert",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
        // TODO add your handling code here:
        if(jTextField5.getText().equals("")==true)
        {
            jTextField5.setText("Enter id");
            jTextField5.setForeground(new java.awt.Color(102,102,102));
        }
    }//GEN-LAST:event_jTextField5FocusLost

    private void jTextField5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusGained
        // TODO add your handling code here:
        if(jTextField5.getText().equals("Enter id")==true)
        {
            jTextField5.setText("");
            jTextField5.setForeground(new java.awt.Color(0,0,0));
        }
    }//GEN-LAST:event_jTextField5FocusGained

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        if(model3!=null)
        {
            if(jTable1.getRowCount()>0)
                model3.setRowCount(0);
        }
        
        if(jTextField5.getText().equals("Enter id")==false)
        {
            try{
                rs=stmt.executeQuery("select * from medicine_patient where patient_id='"+jTextField5.getText()+"'");
                while(rs.next())
                {
                    String str1[],str2[];
                   str1=rs.getString(1).split(" ");
                   str2=rs.getString(5).split("  ");
          
                  model3.addRow(new Object[]{rs.getString(4),str1[0],str1[2],str2[1]+" id: "+str2[0],rs.getString(6),str1[1]});
                    
                }
               
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
            }
        else
        {
                  JOptionPane.showMessageDialog(this,"Enter id");
        }
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
         if(jTextArea3.getText().equals("")==false)
        {
            try{
                stmt.executeUpdate("insert into complaint values('staff_medicine','"+jTextArea3.getText()+"')");
                JOptionPane.showMessageDialog(this,"WE will work on this issue");
                jTextArea3.setText("");
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Fill Complaint","Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jTextField3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField3CaretUpdate
        // TODO add your handling code here:
        try{
           rs=stmt.executeQuery("select * from patient where patient_id='"+jTextField3.getText()+"'");
           if(rs.next())
           {
               jLabel9.setVisible(false);
               jTextField4.setText(rs.getString(1));
           }
           else
           {
               jLabel9.setVisible(true);
               jTextField4.setText("");
           }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jTextField3CaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staff_medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staff_medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staff_medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staff_medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staff_medicine().setVisible(true);
            }
        });
    }
 private void setIconImage() {
            setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
