/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainpackage;
import java.sql.*;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rohith pavan
 */
public class staff_reciopnist extends javax.swing.JFrame {
   Connection c;
 Statement stmt;
 ResultSet rs,rs1;
DefaultTableModel model,model2;
    public staff_reciopnist() {
        initComponents();
         setIconImage();
      
         try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        c=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital?autoReconnect=true&useSSL=false","root","1234");
        stmt=c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
    ResultSet.CONCUR_READ_ONLY);
        }
        catch(Exception e)
        {
          System.out.println(e);
        }
    }
    int countDigits(int num)
    {
        int count=0;
        while(num!=0)
        {
            num=num/10;
            count++;
        }
        return count;
    }
    String p_id( )
    {
        StringBuffer sb=new StringBuffer();
         String a="";
        java.util.Date date1=new java.util.Date();
        String doj[]=new SimpleDateFormat("yyyy-MM-dd").format(date1).split("-");
         int num=Integer.parseInt(doj[0]);
         doj[0]=Integer.toString(num%100);
        sb.append(doj[0]);
        sb.append("hm");
        
        try{
            rs1=stmt.executeQuery("select * from patient");
            if(rs1.last())
            {
                a=rs1.getString("patient_id");
            }
            if(a.length()>0)
            {
                String s1,s2;
                s1=a.substring(0,4);
                s2=a.substring(4);
                if(countDigits(Integer.parseInt(s2)+1)==1)
                {
                    sb.append("000");
                    sb.append(Integer.toString(Integer.parseInt(s2)+1));
                }
                 if(countDigits(Integer.parseInt(s2)+1)==2)
                {
                    sb.append("00");
                    sb.append(Integer.toString(Integer.parseInt(s2)+1));
                }
                  if(countDigits(Integer.parseInt(s2)+1)==3)
                {
                    sb.append("0");
                    sb.append(Integer.toString(Integer.parseInt(s2)+1));
                }
                   if(countDigits(Integer.parseInt(s2)+1)==4)
                {
                    sb.append(Integer.toString(Integer.parseInt(s2)+1));
                }
            }
            else
            {
                sb.append("0001");
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        return sb.toString();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 800));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1500, 800));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("    HOME");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 20, 160, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("APPOINTMENT");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 120, 180, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("  COMPLAINT");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 200, 180, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("    LOGOUT");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 700, 180, 50);

        jLabel22.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("REMEMBER");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel22MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel22MouseExited(evt);
            }
        });
        jPanel1.add(jLabel22);
        jLabel22.setBounds(10, 300, 160, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 180, 810);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);
        jTabbedPane1.addTab("tab1", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jPanel5.setLayout(null);

        jComboBox1.setEnabled(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox1);
        jComboBox1.setBounds(20, 130, 190, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("SELECT DOCTOR:");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(20, 80, 200, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PATIENT ID", "TIME"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setShowHorizontalLines(true);
        jTable1.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(10, 230, 452, 490);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("SCHEDULE OF DOCTOR");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(20, 170, 430, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("PATIENT NAME:");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(530, 310, 150, 40);
        jPanel5.add(jTextField1);
        jTextField1.setBounds(720, 310, 490, 40);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("PATIENT ID:");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(530, 370, 140, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLabel10);
        jLabel10.setBounds(720, 370, 160, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("PATIENT NUMBER:");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(530, 410, 170, 40);

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        jPanel5.add(jTextField2);
        jTextField2.setBounds(720, 420, 180, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("PROBLEM:");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(530, 590, 110, 40);

        jTextArea1.setLineWrap(true);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel5.add(jScrollPane2);
        jScrollPane2.setBounds(730, 600, 290, 110);
        jPanel5.add(jDateChooser1);
        jDateChooser1.setBounds(610, 150, 260, 40);
        jPanel5.add(jSeparator1);
        jSeparator1.setBounds(490, 293, 790, 10);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator2);
        jSeparator2.setBounds(490, 300, 10, 340);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator3);
        jSeparator3.setBounds(490, 0, 3, 290);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("TIME:");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(520, 50, 60, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("DATE:");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(530, 140, 70, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "2", "3", "4", "5", "7", "8", "9", "10", "11", "12", "" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox2);
        jComboBox2.setBounds(640, 50, 80, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "30" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox3);
        jComboBox3.setBounds(770, 50, 80, 30);

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Hours");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(650, 20, 70, 16);

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Minutes");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(770, 20, 70, 16);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Problem:");
        jPanel5.add(jLabel19);
        jLabel19.setBounds(20, 20, 110, 30);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-none-", "CARDIOLOGIST", "DENTIST", "ENT SPECIALIST", "PSYCHIOTRISTS", "ORTHOPAEDIC SURGEON" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox5);
        jComboBox5.setBounds(140, 20, 210, 30);

        jLabel20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("AGE:");
        jPanel5.add(jLabel20);
        jLabel20.setBounds(530, 480, 90, 30);

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });
        jPanel5.add(jTextField3);
        jTextField3.setBounds(720, 480, 80, 30);

        jLabel21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Gender:");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(530, 530, 100, 30);

        jRadioButton3.setForeground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("male");
        jPanel5.add(jRadioButton3);
        jRadioButton3.setBounds(720, 530, 49, 20);

        jRadioButton4.setForeground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("female");
        jPanel5.add(jRadioButton4);
        jRadioButton4.setBounds(720, 560, 60, 20);

        jButton3.setVisible(false);
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("SHEDULE");
        jButton3.setBorder(null);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel5.add(jButton3);
        jButton3.setBounds(610, 200, 120, 30);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(60, 0, 1290, 730);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("SAVE");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(1180, 740, 130, 30);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("CANCEL");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(1180, 780, 130, 30);

        jTabbedPane1.addTab("tab2", jPanel3);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(null);

        jTextArea3.setLineWrap(true);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        jPanel9.add(jScrollPane4);
        jScrollPane4.setBounds(20, 30, 530, 330);

        jButton5.setBackground(new java.awt.Color(0, 102, 0));
        jButton5.setFont(new java.awt.Font("Arial", 3, 28)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("COMPLAINT");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel9.add(jButton5);
        jButton5.setBounds(340, 370, 200, 60);

        jTabbedPane1.addTab("tab3", jPanel9);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(null);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "PATIENT ID", "PATIENT NAME", "NUMBER"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setShowHorizontalLines(true);
        jTable3.setShowVerticalLines(true);
        jTable3.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(jTable3);

        jPanel7.add(jScrollPane5);
        jScrollPane5.setBounds(20, 20, 930, 780);

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setText("CANCEL APPOINTMENT");
        jButton7.setBorder(null);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jPanel7.add(jButton7);
        jButton7.setBounds(980, 410, 320, 30);

        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setText("REMEMBERED");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel7.add(jButton4);
        jButton4.setBounds(980, 460, 320, 30);

        jTabbedPane1.addTab("tab6", jPanel7);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(180, -40, 1320, 850);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        dispose();
        new Loginpage().setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(1);
           java.util.Date date1=new java.util.Date();
           jDateChooser1.setDate(date1);
           jLabel10.setText(p_id());
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(2);
         
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
          jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
         jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
          jLabel2.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
         jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
          jLabel4.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
         jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
          jLabel5.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        // TODO add your handling code here:
         jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel5MouseExited

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
         if(model!=null)
            model.setRowCount(0);
        String str;
         jComboBox1.removeAllItems();
         jComboBox1.setEnabled(false);
          jButton3.setVisible(false);
         if(jComboBox5.getSelectedIndex()>0)
        if(jComboBox5.getSelectedItem().toString().equalsIgnoreCase("-none-")==false)
        {
            jComboBox1.setEnabled(true);
           
            jComboBox1.addItem("-none-");
            str=jComboBox5.getSelectedItem().toString();
            try{
            rs=stmt.executeQuery("select * from info where specialised='"+str+"'");
            while(rs.next())
            {
                jComboBox1.addItem(rs.getString("user_id")+" "+rs.getString("name"));
            }
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
           
        }
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        if(model!=null)
        {
            if(model.getRowCount()>0)
            {
                model.setRowCount(0);
            }
        }
         if(jComboBox1.getSelectedIndex()>0)
        if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase("-none-")==false)
        {
          model=(DefaultTableModel) jTable1.getModel();
              String str[]=jComboBox1.getSelectedItem().toString().split(" ");
             jButton3.setVisible(true);
               java.util.Date date1=new java.util.Date();
       String doj=new SimpleDateFormat("yyyy-MM-dd").format(date1);
              try{
              rs=stmt.executeQuery("select * from patient where doctor_id='"+str[0]+"' and date='"+doj+"'");
              
                   while(rs.next())
                  model.addRow(new Object[]{rs.getString("patient_id")+" "+rs.getString("Patient_name"),rs.getString("time")});
              
              
              }
              catch(Exception e)
              {
                  System.out.println(e);
              }
               
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
         Calendar calendar = Calendar.getInstance();
    java.util.Date today = calendar.getTime();
    calendar.add(Calendar.DAY_OF_YEAR, 1);
    java.util.Date tomorrow = calendar.getTime();
    String str=new SimpleDateFormat("yyyy-MM-dd").format(tomorrow);
    try{
        rs=stmt.executeQuery("select * from patient where date='"+str+"'");
         model2=(DefaultTableModel) jTable3.getModel();
        if(model2!=null)
        {
            if(model2.getRowCount()>0)
            {
                model2.setRowCount(0);
            }
        }
          while(rs.next())
                  model2.addRow(new Object[]{rs.getString("patient_id"),rs.getString("Patient_name"),rs.getString("number")});
    }
    catch(Exception e)
    {
        System.out.println(e);
    }
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jLabel22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseEntered
        // TODO add your handling code here:
          jLabel22.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_jLabel22MouseEntered

    private void jLabel22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseExited
        // TODO add your handling code here
          jLabel22.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_jLabel22MouseExited

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
         if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')||(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE)) 
               jTextField3.setEditable(true);
         else
               jTextField3.setEditable(false);
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
         if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')||(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE)) 
               jTextField2.setEditable(true);
         else
               jTextField2.setEditable(false);
        
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String doc_id,time_min,time_hour,date,patient_num,gender="",problem,doc[],time;
                int age;
                StringBuffer sb=new StringBuffer();
                int count=0;
                String name;
        try{
            
            if(jComboBox1.getSelectedIndex()>0&&jComboBox2.getSelectedIndex()>0&&jComboBox3.getSelectedIndex()>=0&&jTextField1.getText().equalsIgnoreCase("")==false&&jTextField2.getText().equalsIgnoreCase("")==false&&jTextField3.getText().equalsIgnoreCase("")==false&&jTextArea1.getText().equalsIgnoreCase("")==false&&(jRadioButton3.isSelected()||jRadioButton4.isSelected()))
            {
                int count2=0;
                doc=jComboBox1.getSelectedItem().toString().split(" ");
                doc_id=doc[0];
                time_min=jComboBox3.getSelectedItem().toString();
                time_hour=jComboBox2.getSelectedItem().toString();
                sb.append(time_hour);
                sb.append(":");
                sb.append(time_min);
                sb.append(":");
                sb.append("00");
                date=new SimpleDateFormat("yyyy-MM-dd").format(jDateChooser1.getDate());
                patient_num=jTextField2.getText();
                if(jRadioButton3.isSelected())
                    gender="male";
                if(jRadioButton4.isSelected())
                    gender="female";
                problem=jTextArea1.getText();
                age=Integer.parseInt(jTextField3.getText());
                name=jTextField1.getText();
               rs=stmt.executeQuery("select count(patient_id) from patient where time='"+sb.toString()+"' and doctor_id='"+doc_id+"' and date='"+date+"'");
               if(rs.next())
               count=Integer.parseInt(rs.getString(1));
               rs=stmt.executeQuery("select count(patient_id) from patient where patient_regard='operation' and doctor_id='"+doc_id+"' and date='"+date+"'");
                if(rs.next())
               count2=Integer.parseInt(rs.getString(1));
               if(count==0&&count2==0)
               {
                   stmt.executeUpdate("insert into patient(Patient_name,patient_id,age,gender,problem,date,number,time,doctor_id) values('"+name+"','"+jLabel10.getText()+"',"+age+",'"+gender+"','"+problem+"','"+date+"','"+patient_num+"','"+sb.toString()+"','"+doc_id+"')");
                   JOptionPane.showMessageDialog(this,"registered succesful on"+" "+date,"Alert",JOptionPane.PLAIN_MESSAGE);
                   jComboBox5.setSelectedIndex(0);
                   jComboBox1.setEnabled(false);
                    jComboBox2.setSelectedIndex(0);
                     jComboBox3.setSelectedIndex(0);
                      java.util.Date date1=new java.util.Date();
           jDateChooser1.setDate(date1);
                      jTextField1.setText("");
                       jTextField2.setText("");
                        jTextField3.setText("");
                        jTextArea1.setText("");
                        jLabel10.setText(p_id());
                        jButton3.setVisible(false);
                        buttonGroup2.clearSelection();
                        if(model!=null)
                           {
                             if(model.getRowCount()>0)
                                {
                                     model.setRowCount(0);
                                }
                           }
               }
               else
               {
                   if(count2!=0)
                   {
                      JOptionPane.showMessageDialog(this,"Doctor in operation","Alert",JOptionPane.ERROR_MESSAGE);  
                     count=0;
                   }
                      if(count!=0)
                    JOptionPane.showMessageDialog(this,"Doctor In work","Alert",JOptionPane.WARNING_MESSAGE);
                   
               }
                   
               
            }
            else
            {
                 JOptionPane.showMessageDialog(this,"Fill all the fields","Alert",JOptionPane.ERROR_MESSAGE); 
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
         jComboBox5.setSelectedIndex(0);
                   jComboBox1.setEnabled(false);
                    jComboBox2.setSelectedIndex(0);
                     jComboBox3.setSelectedIndex(0);
                       java.util.Date date1=new java.util.Date();
           jDateChooser1.setDate(date1);
                      jTextField1.setText("");
                       jTextField2.setText("");
                        jTextField3.setText("");
                        jTextArea1.setText("");
                        jLabel10.setText(p_id());
                        buttonGroup2.clearSelection();
                        jButton3.setVisible(false);
                        if(model!=null)
                           {
                             if(model.getRowCount()>0)
                                {
                                     model.setRowCount(0);
                                }
                           }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
         if(model!=null)
        {
            if(model.getRowCount()>0)
            {
                model.setRowCount(0);
            }
        }
         if(jComboBox1.getSelectedIndex()>0&&jComboBox1.isEnabled()==true)
        if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase("-none-")==false)
        {
          model=(DefaultTableModel) jTable1.getModel();
              String str[]=jComboBox1.getSelectedItem().toString().split(" ");
             jButton3.setVisible(true);
               
       String doj=new SimpleDateFormat("yyyy-MM-dd").format(jDateChooser1.getDate());
              try{
              rs=stmt.executeQuery("select * from patient where doctor_id='"+str[0]+"' and date='"+doj+"'");
              
                   while(rs.next())
                  model.addRow(new Object[]{rs.getString("patient_id")+" "+rs.getString("Patient_name"),rs.getString("time")});
              
              
              }
              catch(Exception e)
              {
                  System.out.println(e);
              }
               
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        int row=jTable3.getSelectedRow();
        String str=jTable3.getModel().getValueAt(row,0).toString();
        try{
            stmt.executeUpdate("delete from patient where patient_id='"+str+"'");
            model2.removeRow(row);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        int row=jTable3.getSelectedRow();
        String str=jTable3.getModel().getValueAt(row,0).toString();
            model2.removeRow(row);
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
         if(jTextArea3.getText().equals("")==false)
        {
            try{
                stmt.executeUpdate("insert into complaint values('staff_reciopnist','"+jTextArea3.getText()+"')");
                JOptionPane.showMessageDialog(this,"WE will work on this issue");
                jTextArea3.setText("");
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Fill Complaint","Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staff_reciopnist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staff_reciopnist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staff_reciopnist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staff_reciopnist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staff_reciopnist().setVisible(true);
            }
        });
    }
 private void setIconImage() {
            setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
